language: python

python:
  - "3.3"
  - "3.4"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then travis_retry pip install enum34; fi
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install coveralls
  - travis_retry pip install flake8
  - travis_retry pip install sphinx

before_script:
  - flake8 --max-line-length=120 regatta
  - (cd docs; make html)

script:
  - PYTHONPATH=`pwd` coverage run --source=regatta -m py.test

after_success:
  - coveralls
