language: python

python:
  - "3.3"
  - "3.4"

install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then travis_retry pip install enum34; fi
  - pip install coveralls
  - pip install flake8

before_script:
  - flake8 --max-line-length=120 regatta

script:
  - PYTHONPATH=`pwd` coverage run --source=regatta -m py.test

after_success:
  - coveralls
