language: python

python:
  - "3.3"
  - "3.4"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install flake8

before_script:
  - flake8 --max-line-length=120 regatta

script:
  - coverage run --source=regatta -m py.test

after_success:
  - coveralls
