language: python

python:
  - "3.3"
  - "3.4"

install: 
  - pip install -r requirements.txt
  - pip install -U pytest-cov
  - pip install -U python-coveralls

script:
  py.test --cov=.

after_success:
  coveralls
